site_name: "OMG dazzling docs"
site_description: "Truely a becon shining down on a shadowy world of lesser docs"
docs_dir: "docs"
repo_url: "https://github.com/bcgov/devhub-transfer-test"
edit_uri: edit/main/docs
nav:
    - Introduction: index.md
    - Getting started: getting-started.md
    - Configuration: configuration.md
    - Tips and tricks: tips-and-tricks.md
    - About us: about-us.md
plugins:
    - techdocs-core
    - git-revision-date-localized
markdown_extensions:
    - md_in_html
